- rust/operator/src/lib.rs
> Setting metastore.warehouse.dir to /stackable/warehouse

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deploy/helm/hive-operator/crds/crds.yaml
- docs/modules/hive/partials/supported-versions.adoc
- examples/simple-hive-cluster.yaml
- rust/crd/src/affinity.rs
- rust/crd/src/lib.rs
- rust/operator-binary/src/controller.rs
- tests/templates/kuttl/logging/01-install-hbase-vector-aggregator.yaml
- tests/test-definition.yaml
- remove all references to 2.3.9
- use jmx-exporter softlink
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Adapt to docker image changes

- Cargo.lock
- Cargo.toml
- rust/crd/src/lib.rs
- rust/operator-binary/Cargo.toml
- rust/operator-binary/src/controller.rs
Part of https://github.com/stackabletech/product-config/issues/95
> refactor: Use updated product-config

- CHANGELOG.md
- docs/modules/hive/pages/discovery.adoc
- rust/operator-binary/src/discovery.rs
- Use metastore service instead of single pod references in discovery config map to enable HA
fixes https://github.com/stackabletech/hive-operator/issues/380
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Use service in discovery configmap

- CHANGELOG.md
- deploy/helm/hive-operator/crds/crds.yaml
- docs/modules/hive/pages/usage-guide/operations/graceful-shutdown.adoc
- rust/crd/src/lib.rs
- rust/operator-binary/src/command.rs
- rust/operator-binary/src/controller.rs
- rust/operator-binary/src/operations/graceful_shutdown.rs
- rust/operator-binary/src/operations/mod.rs
- tests/templates/kuttl/smoke/60-assert.yaml.j2
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> feat: Support graceful shutdown

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deploy/helm/hive-operator/crds/crds.yaml
- rust/crd/src/lib.rs
- rust/operator-binary/src/main.rs
better CRD docs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> feat: Better CRD docs

- tests/templates/kuttl/kerberos-hdfs/00-rbac.yaml.j2
- tests/templates/kuttl/kerberos-hdfs/01-install-krb5-kdc.yaml.j2
- tests/templates/kuttl/kerberos-hdfs/35-access-hdfs.yaml.j2
- tests/templates/kuttl/kerberos-hdfs/70-install-access-hive.yaml.j2
- tests/templates/kuttl/kerberos-s3/00-rbac.yaml.j2
- tests/templates/kuttl/kerberos-s3/01-install-krb5-kdc.yaml.j2
- tests/templates/kuttl/kerberos-s3/70-install-access-hive.yaml.j2
fix kerberos tests on openshift
```
--- PASS: kuttl (1201.26s)
--- PASS: kuttl/harness/smoke_postgres-12.5.6_hive-3.1.3_openshift-true_s3-use-tls-true (202.57s)
--- PASS: kuttl/harness/kerberos-hdfs_postgres-12.5.6_hive-3.1.3_hdfs-latest-3.3.6_zookeeper-latest-3.8.3_openshift-true_kerberos-realm-PROD.MYCORP_kerberos-backend-mit (371.53s)
--- PASS: kuttl/harness/logging_postgres-12.5.6_hive-3.1.3_openshift-true (127.96s)
--- PASS: kuttl/harness/resources_hive-3.1.3 (34.17s)
--- PASS: kuttl/harness/cluster-operation_hive-latest-3.1.3 (148.84s)
--- PASS: kuttl/harness/kerberos-s3_postgres-12.5.6_hive-3.1.3_openshift-true_s3-use-tls-true_kerberos-realm-PROD.MYCORP_kerberos-backend-mit (223.01s)
--- PASS: kuttl/harness/orphaned-resources_hive-latest-3.1.3 …
```
> fix: kerberos tests to run on openshift

- docs/modules/hive/examples/getting_started/getting_started.sh
This makes the getting_started script work with the new [stackablectl][1] from [stackable-cockpit][2].
[1]: https://github.com/stackabletech/stackable-cockpit/blob/5837276d8c1e587faa73a43da62cbab67e072b8c/rust/stackablectl/src/args/file.rs#L19-L45
[2]: https://github.com/stackabletech/stackable-cockpit
> fix: stackablectl arguments in getting_started.sh

- docs/modules/hive/pages/index.adoc
- docs/modules/hive/pages/usage-guide/security.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: fix links

- tests/release.yaml
- tests/templates/kuttl/cluster-operation/00-patch-ns.yaml.j2
- tests/templates/kuttl/kerberos-hdfs/00-patch-ns.yaml.j2
- tests/templates/kuttl/kerberos-s3/00-patch-ns.yaml.j2
- tests/templates/kuttl/logging/00-patch-ns.yaml.j2
- tests/templates/kuttl/orphaned-resources/00-patch-ns.yaml.j2
- tests/templates/kuttl/resources/00-patch-ns.yaml.j2
- tests/templates/kuttl/smoke/00-patch-ns.yaml.j2
- tests/test-definition.yaml
Part of stackabletech/issues#566.
OKD:
```
--- PASS: kuttl (610.59s)
--- PASS: kuttl/harness/logging_postgres-12.5.6_hive-3.1.3_openshift-true (182.81s)
--- PASS: kuttl/harness/kerberos-hdfs_postgres-12.5.6_hive-3.1.3_hdfs-latest-3.3.6_zookeeper-latest-3.9.1_openshift-true_kerberos-realm-PROD.MYCORP_kerberos-backend-mit (306.01s)
--- PASS: kuttl/harness/cluster-operation_hive-latest-3.1.3_openshift-true (142.88s)
--- PASS: kuttl/harness/orphaned-resources_hive-latest-3.1.3_openshift-true (77.78s)
--- PASS: kuttl/harness/resources_hive-3.1.3_openshift-true (71.01s)
--- PASS: kuttl/harness/kerberos-s3_postgres-12.5.6_hive-3.1.3_openshift-true_s3-use-tls-true_kerberos-realm-PROD.MYCORP_kerberos-backend-mit (164.38s)
--- PASS: …
```
> tests: added namespace patch for openshift tests

- CHANGELOG.md
- docs/modules/hive/pages/required-external-components.adoc
- docs/modules/hive/pages/usage-guide/database-driver-example.adoc
- docs/modules/hive/pages/usage-guide/database-driver.adoc
- docs/modules/hive/partials/nav.adoc
docs: detail how to mount and use external drivers.
fixes https://github.com/stackabletech/hive-operator/issues/416.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: detail how to mount and use external drivers

- docs/modules/hive/pages/usage-guide/resources.adoc
This fixes an incorrect title seen here: https://docs.stackable.tech/home/stable/hive/usage-guide/resources
> fix(docs): Fix the h2 to a h1 title

- tests/templates/kuttl/kerberos-hdfs/01-install-krb5-kdc.yaml.j2
- tests/templates/kuttl/kerberos-s3/01-install-krb5-kdc.yaml.j2
- tests/test-definition.yaml
Update the krb5 image in the integration tests
The krb5 version was upgraded from 1.18.2 to 1.21.1 in stackabletech/docker-images#627. As the image with version 1.18.2 is not built anymore, it must be replaced in all integration tests.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Update the krb5 image in the integration tests

- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- tests/templates/kuttl/smoke/60-install-hive.yaml.j2
- tests/templates/kuttl/smoke/61-assert.yaml
Part of: https://github.com/stackabletech/issues/issues/548
:green_circle: Test
```shell
$ ./scripts/run-tests --test-suite smoke-latest --skip-release
...
--- PASS: kuttl (209.68s)
--- PASS: kuttl/harness/smoke_postgres-12.5.6_hive-3.1.3_openshift-false_s3-use-tls-false (208.28s)
PASS
```
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix(test): smoke testing env and config overrides

- CHANGELOG.md
- docs/modules/hive/examples/getting_started/hive-postgres-s3.yaml
- docs/modules/hive/examples/getting_started/hive-postgres-s3.yaml.j2
- docs/modules/hive/pages/usage-guide/database-driver.adoc
- docs/modules/hive/pages/usage-guide/derby-example.adoc
- docs/modules/hive/partials/supported-versions.adoc
- examples/simple-hive-cluster-postgres-s3.yaml
- examples/simple-hive-cluster.yaml
- rust/crd/src/affinity.rs
- tests/templates/kuttl/kerberos-s3/70-install-access-hive.yaml.j2
- tests/templates/kuttl/smoke/test_metastore.py
- tests/test-definition.yaml
Part of https://github.com/stackabletech/issues/issues/620
Needs https://github.com/stackabletech/docker-images/pull/818
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> feat: Add support for Hive 4.0.0

- tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/835
```
--- PASS: kuttl (442.13s)
--- PASS: kuttl/harness/kerberos-hdfs_postgres-12.5.6_hive-4.0.0_hdfs-latest-3.4.0_zookeeper-latest-3.9.2_krb5-1.21.1_openshift-false_kerberos-realm-PROD.MYCORP_kerberos-backend-mit (426.80s)
--- PASS: kuttl/harness/kerberos-hdfs_postgres-12.5.6_hive-3.1.3_hdfs-latest-3.4.0_zookeeper-latest-3.9.2_krb5-1.21.1_openshift-false_kerberos-realm-PROD.MYCORP_kerberos-backend-mit (441.33s)
PASS
```
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: bump hdfs version to 3.4.0

- docs/modules/hive/pages/getting_started/first_steps.adoc
- docs/modules/hive/pages/getting_started/index.adoc
- docs/modules/hive/pages/getting_started/installation.adoc
- docs/modules/hive/pages/index.adoc
- docs/modules/hive/pages/required-external-components.adoc
- docs/modules/hive/pages/usage-guide/configuration-environment-overrides.adoc
- docs/modules/hive/pages/usage-guide/data-storage.adoc
- docs/modules/hive/pages/usage-guide/database-driver.adoc
- docs/modules/hive/pages/usage-guide/derby-example.adoc
- docs/modules/hive/pages/usage-guide/index.adoc
- docs/modules/hive/pages/usage-guide/listenerclass.adoc
- docs/modules/hive/pages/usage-guide/logging.adoc
- docs/modules/hive/pages/usage-guide/monitoring.adoc
- docs/modules/hive/pages/usage-guide/resources.adoc
- docs/modules/hive/pages/usage-guide/security.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Add descriptions

- docs/modules/hive/pages/getting_started/first_steps.adoc
- docs/modules/hive/pages/getting_started/index.adoc
- docs/modules/hive/pages/getting_started/installation.adoc
- docs/modules/hive/pages/index.adoc
- docs/modules/hive/pages/reference/commandline-parameters.adoc
- docs/modules/hive/pages/reference/environment-variables.adoc
- docs/modules/hive/pages/usage-guide/configuration-environment-overrides.adoc
- docs/modules/hive/pages/usage-guide/database-driver.adoc
- docs/modules/hive/pages/usage-guide/derby-example.adoc
- docs/modules/hive/pages/usage-guide/index.adoc
- docs/modules/hive/pages/usage-guide/operations/graceful-shutdown.adoc
- docs/modules/hive/pages/usage-guide/operations/index.adoc
- docs/modules/hive/pages/usage-guide/operations/pod-disruptions.adoc
- docs/modules/hive/pages/usage-guide/security.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: pod overrides

- CHANGELOG.md
- rust/operator-binary/src/controller.rs
- rust/operator-binary/src/main.rs
Part of: https://github.com/stackabletech/issues/issues/211
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix: don't stop reconciliation if one cluster is invalid

- docs/modules/hive/pages/reference/environment-variables.adoc
Adds missing KUBERNETES_CLUSTER_DOMAIN environment variable to docs
part of stackabletech/issues#668
> Adds missing KUBERNETES_CLUSTER_DOMAIN environment variable to docs

- CHANGELOG.md
- rust/crd/src/lib.rs
- rust/operator-binary/src/controller.rs
- tests/templates/kuttl/upgrade/00-limit-range.yaml
- tests/templates/kuttl/upgrade/00-patch-ns.yaml.j2
- tests/templates/kuttl/upgrade/10-assert.yaml.j2
- tests/templates/kuttl/upgrade/10-install-vector-aggregator-discovery-configmap.yaml.j2
- tests/templates/kuttl/upgrade/20-assert.yaml
- tests/templates/kuttl/upgrade/20-install-postgres.yaml.j2
- tests/templates/kuttl/upgrade/30-assert.yaml.j2
- tests/templates/kuttl/upgrade/30-install-hive.yaml.j2
- tests/templates/kuttl/upgrade/31-assert.yaml.j2
- tests/templates/kuttl/upgrade/31-upgrade-hive.yaml.j2
- tests/templates/kuttl/upgrade/helm-bitnami-postgresql-values.yaml.j2
- tests/test-definition.yaml
Fixes https://github.com/stackabletech/hive-operator/issues/538
This PR also adds an upgrade test to make sure the functionality will be kept going forward.
Co-developed with @xeniape
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix: Fix upgrade path 3.3.x -> 4.0.x

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Use patched version of op-rs that hopefully addresses SUP-148. 

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- docs/modules/hive/examples/getting_started/getting_started.sh
When running the minio installation command, the following error is thrown:
```
helm install minio \
--version 4.0.2 \
--namespace default \
--set mode=standalone \
--set replicas=1 \
--set persistence.enabled=false \
--set buckets[0].name=hive,buckets[0].policy=none \
--set users[0].accessKey=hive,users[0].secretKey=hivehive,users[0].policy=readwrite \
--set resources.requests.memory=1Gi \
--set service.type=NodePort,service.nodePort=null \
--set consoleService.type=NodePort,consoleService.nodePort=null \
--repo https://charts.min.io/ minio
zsh: no matches found: buckets[0].name=hive,buckets[0].policy=none
```
This PR adds double quotes to the two settings throwing this error, which fixes it.
Edit: Also bumped `stackable-operator` version as part of this PR due to `cargo deny` errors.
> chore: bump stackable-operator version and fix minio installation command

- CHANGELOG.md
- deploy/helm/hive-operator/crds/crds.yaml
- docs/modules/hive/pages/usage-guide/overrides.adoc
- docs/modules/hive/partials/nav.adoc
- rust/operator-binary/src/config/jvm.rs
- rust/operator-binary/src/config/mod.rs
- rust/operator-binary/src/controller.rs
- rust/operator-binary/src/crd/mod.rs
- rust/operator-binary/src/main.rs
- tests/templates/kuttl/resources/20-assert.yaml
- tests/templates/kuttl/smoke/60-install-hive.yaml.j2
- tests/templates/kuttl/smoke/61-assert.yaml
Part of https://github.com/stackabletech/issues/issues/584
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> feat!: Support configuring JVM arguments

- docs/modules/hive/pages/usage-guide/data-storage.adoc
Clarify on SUP-176
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: Document why we need storage connections

- CHANGELOG.md
- docs/modules/hive/pages/usage-guide/resources.adoc
- rust/operator-binary/src/config/jvm.rs
- rust/operator-binary/src/crd/mod.rs
- tests/templates/kuttl/kerberos-hdfs/60-assert.yaml.j2
- tests/templates/kuttl/kerberos-s3/60-assert.yaml.j2
- tests/templates/kuttl/smoke/60-assert.yaml.j2
Increase the default memory reservation to `768Mi` to avoid OOMKilled.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix: Bump default memory reservation to 768Mi

- docs/modules/hive/examples/getting_started/getting_started.sh
- docs/modules/hive/examples/getting_started/getting_started.sh.j2
- docs/modules/hive/pages/getting_started/installation.adoc
- docs/modules/hive/pages/usage-guide/derby-example.adoc
- docs/templating_vars.yaml
- examples/simple-hive-cluster-postgres-s3.yaml
Part of https://github.com/stackabletech/infrastructure/issues/142
Updating the helm install commands in Getting started sections of the operators was missed during Harbor migration of the docs.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: Update helm install commands

- CHANGELOG.md
- tests/templates/kuttl/logging/01-install-hbase-vector-aggregator.yaml
- tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1085.
- Bump to Vector 0.46.1 (chart version 0.42.1) in tests
> test: Bump vector to 0.46.1

- CHANGELOG.md
- rust/operator-binary/src/controller.rs
- tests/templates/kuttl/kerberos-hdfs/35-access-hdfs.yaml.j2
- tests/templates/kuttl/kerberos-hdfs/70-install-access-hive.yaml.j2
- tests/templates/kuttl/kerberos-s3/70-install-access-hive.yaml.j2
Part of https://github.com/stackabletech/issues/issues/651
Remove hardcoded uid and gid, they'll default to the ones from the docker images now.
For 25.7 that means they might change from 1000/0
See https://github.com/stackabletech/docker-images/pull/916 for details
> chore: Remove hardcoded uid and gid

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- rust/operator-binary/src/command.rs
- rust/operator-binary/src/controller.rs
- rust/operator-binary/src/crd/mod.rs
Part of https://github.com/stackabletech/issues/issues/642.
Bump stackable-operator to 0.93.1 which versions common CRD structs.
> chore: Bump stackable_operator to 0.93.1

- tests/templates/kuttl/cluster-operation/10-assert.yaml
- tests/templates/kuttl/kerberos-hdfs/60-assert.yaml.j2
- tests/templates/kuttl/kerberos-s3/60-assert.yaml.j2
- tests/templates/kuttl/logging/04-assert.yaml
- tests/templates/kuttl/orphaned-resources/01-assert.yaml
- tests/templates/kuttl/resources/10-assert.yaml.j2
- tests/templates/kuttl/smoke/60-assert.yaml.j2
- tests/templates/kuttl/upgrade/30-assert.yaml.j2
Sometimes it takes longer than 10 minutes to create a `HiveCluster` in our weekly tests. I found test runs where for some reason the listener Pod on a node took a long time to start, which in turn blocked the Hive pods from starting. Mostly this succeeds shortly after the current timeout of 10 minutes, so I increased the timeout to 15 minutes. 
> tests: increase HiveCluster assert timeouts

- CHANGELOG.md
- rust/operator-binary/src/controller.rs
- rust/operator-binary/src/crd/mod.rs
- rust/operator-binary/src/discovery.rs
- rust/operator-binary/src/listener.rs
- rust/operator-binary/src/main.rs
- rust/operator-binary/src/service.rs
- tests/templates/kuttl/external-access/20-assert.yaml
- tests/templates/kuttl/smoke/80-assert.yaml
This PR adopts hive according to https://github.com/stackabletech/decisions/issues/54#issue-3110829918
> Listener: Use headless and metrics service

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- deploy/helm/hive-operator/crds/crds.yaml
- deploy/helm/hive-operator/templates/roles.yaml
- rust/operator-binary/src/controller.rs
- rust/operator-binary/src/crd/mod.rs
- rust/operator-binary/src/main.rs
Part of <https://github.com/stackabletech/issues/issues/725>
> [!NOTE]
> During a Stackable release we need to update various Rust dependencies before
> entering the final release period to ensure we run the latest versions of
> crates. These bumps also include previously updated and released crates from
> the `operator-rs` repository.
> [!NOTE]
> The bumping / updating of Rust dependencies is done in multiple steps:
>
> 1. Update the minimum Version in the root `Cargo.toml` manifest.
> 2. Run the `cargo update` command, which also updates the `Cargo.lock` file.
> 3. Lastly, run `make regenerate-nix` to update the `Cargo.nix` file.
> chore: Bump Rust dependencies pre-25.7.0

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- deploy/helm/hive-operator/Chart.yaml
- deploy/helm/hive-operator/crds/crds.yaml
- docs/antora.yml
- docs/modules/hive/examples/getting_started/getting_started.sh
- docs/modules/hive/examples/getting_started/install-operator-output.txt
- docs/modules/hive/examples/getting_started/release.yaml
- docs/templating_vars.yaml
- tests/release.yaml
- tests/templates/kuttl/upgrade/30-assert.yaml.j2
- tests/templates/kuttl/upgrade/31-assert.yaml.j2
> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.
> chore: Release 25.7.0-rc1

- CHANGELOG.md
- deploy/helm/hive-operator/templates/roles.yaml
Needed since https://github.com/stackabletech/operator-rs/pull/938
Not 100% sure why the product needs this, but it was this way before.
> fix: Add RBAC permission to patch events

- docs/modules/hive/examples/getting_started/getting_started.sh
- docs/modules/hive/examples/getting_started/getting_started.sh.j2
- docs/modules/hive/examples/getting_started/postgres-stack.yaml
- docs/modules/hive/examples/getting_started/postgres-stack.yaml.j2
- docs/modules/hive/pages/usage-guide/database-driver.adoc
- docs/modules/hive/pages/usage-guide/derby-example.adoc
- examples/simple-hive-cluster-postgres-s3.yaml
- tests/templates/kuttl/kerberos-hdfs/helm-bitnami-postgresql-values.yaml.j2
- tests/templates/kuttl/kerberos-s3/helm-bitnami-minio-values.yaml.j2
- tests/templates/kuttl/kerberos-s3/helm-bitnami-postgresql-values.yaml.j2
- tests/templates/kuttl/logging/helm-bitnami-postgresql-values.yaml.j2
- tests/templates/kuttl/smoke/helm-bitnami-minio-values.yaml.j2
- tests/templates/kuttl/smoke/helm-bitnami-postgresql-values.yaml.j2
- tests/templates/kuttl/upgrade/helm-bitnami-postgresql-values.yaml.j2
Part of https://github.com/stackabletech/issues/issues/749 Quickfix
This PR updates the tests and docs to use the bitnamylegacy repository for bitnami images. All affected tests, commands and getting started scripts ran successfully.
Integrationstests:
```
--- PASS: kuttl (635.40s)
--- PASS: kuttl/harness/kerberos-hdfs_postgres-12.5.6_hive-4.0.1_hdfs-latest-3.4.1_zookeeper-latest-3.9.3_krb5-1.21.1_openshift-false_kerberos-realm-PROD.MYCORP_kerberos-backend-mit (370.21s)
--- PASS: kuttl/harness/kerberos-hdfs_postgres-12.5.6_hive-3.1.3_hdfs-latest-3.4.1_zookeeper-latest-3.9.3_krb5-1.21.1_openshift-false_kerberos-realm-PROD.MYCORP_kerberos-backend-mit (370.67s)
--- PASS: kuttl/harness/kerberos-hdfs_postgres-12.5.6_hive-4.0.0_hdfs-latest-3.4.1_zookeeper-latest-3 …
```
> chore: update tests and docs to use bitnamilegacy

- docs/modules/hive/partials/supported-versions.adoc
Part of https://github.com/stackabletech/hive-operator/issues/626
> docs: clarify Hive 4 support
