CHANGELOG.md, Cargo.lock, deploy/helm/hive-operator/Chart.yaml, deploy/manifests/configmap.yaml, deploy/manifests/deployment.yaml, deploy/manifests/serviceaccount.yaml, rust/crd/Cargo.toml, rust/operator-binary/Cargo.toml, rust/operator/Cargo.toml
Release 0.3.0. DO NOT SQUASH MERGE!
=> Release 0.3.0

CHANGELOG.md, rust/operator-binary/src/main.rs
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)
=> Shutdown on SIGTERM

Cargo.lock, README.adoc, README.md, rust/operator-binary/Cargo.toml, rust/operator-binary/src/controller.rs
- README update
- Dependency updates
- Remove unused dependencies
- Rustdoc fixes
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)
=> Various changes

Cargo.lock, deploy/helm/hive-operator/Chart.yaml, deploy/manifests/configmap.yaml, deploy/manifests/deployment.yaml, deploy/manifests/serviceaccount.yaml, docs/antora.yml, docs/modules/getting_started/examples/code/getting-started.sh, docs/modules/getting_started/examples/code/install-operator-output.txt, docs/templating_vars.yaml, rust/crd/Cargo.toml, rust/operator-binary/Cargo.toml
=> bump version 0.9.0-nightly

CHANGELOG.md, deploy/helm/hive-operator/crds/crds.yaml, rust/crd/src/lib.rs
cherry picked from commit d5d8fabdf6fa81cb5ec76c6a3252b9773eaa70d0
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)
=> Add missing crd defaults

CHANGELOG.md, Cargo.lock, deploy/helm/hive-operator/crds/crds.yaml, docs/modules/hive/examples/getting_started/hive-postgres-s3.yaml, docs/modules/hive/examples/getting_started/hive-postgres-s3.yaml.j2, docs/modules/hive/pages/usage.adoc, rust/crd/Cargo.toml, rust/crd/src/affinity.rs, rust/operator-binary/Cargo.toml, rust/operator-binary/src/controller.rs, rust/operator-binary/src/main.rs, tests/templates/kuttl/cluster-operation/10-install-hive.yaml.j2, tests/templates/kuttl/cluster-operation/20-stop-hive.yaml.j2, tests/templates/kuttl/cluster-operation/30-pause-hive.yaml.j2, tests/templates/kuttl/cluster-operation/40-restart-hive.yaml.j2, tests/templates/kuttl/logging/03-install-hive.yaml.j2, tests/templates/kuttl/orphaned-resources/01-install-hive.yaml.j2, tests/templates/kuttl/orphaned-resources/03-remove-role-group.yaml.j2, tests/templates/kuttl/resources/10-install-hive.yaml.j2, tests/templates/kuttl/smoke/60-install-hive.yaml.j2, tests/test-definition.yaml
Part of https://github.com/stackabletech/issues/issues/404
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: Default stackableVersion to operator version

CHANGELOG.md, tests/kuttl-test.yaml.jinja2, tests/templates/kuttl/logging/01-install-hbase-vector-aggregator.yaml, tests/templates/kuttl/logging/hive-vector-aggregator-values.yaml.j2, tests/templates/kuttl/logging/test_log_aggregation.py
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Upgrade vector

docs/modules/hive/pages/getting_started/installation.adoc, docs/modules/hive/pages/index.adoc, docs/modules/hive/pages/required-external-components.adoc, docs/modules/hive/partials/nav.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> docs: Add external dependencies

CHANGELOG.md, deploy/config-spec/properties.yaml, deploy/helm/hive-operator/configs/properties.yaml, docs/modules/hive/pages/usage.adoc, rust/crd/src/lib.rs, rust/operator-binary/src/controller.rs
CI: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hive-operator-it-custom/39/
Use JVM defaults.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> JVM config overrides

deploy/helm/hive-operator/crds/crds.yaml, docs/modules/hive/pages/usage-guide/listenerclass.adoc, docs/modules/hive/partials/nav.adoc, rust/crd/src/lib.rs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> ListenerClass docs

docs/modules/hive/pages/getting_started/first_steps.adoc, docs/modules/hive/pages/getting_started/installation.adoc, docs/modules/hive/pages/index.adoc
Part of https://github.com/stackabletech/stackable-cockpit/pull/101
=> docs: Update references

docs/modules/hive/pages/getting_started/installation.adoc
Part of https://github.com/stackabletech/stackable-cockpit/pull/101
=> fix(docs): Update invalid references in 23.7

docs/modules/hive/pages/getting_started/installation.adoc
Part of https://github.com/stackabletech/stackable-cockpit/pull/101
=> fix(docs): Update invalid references in 23.4

docs/modules/hive/examples/getting_started/getting_started.sh, docs/modules/hive/examples/getting_started/getting_started.sh.j2, docs/modules/hive/examples/getting_started/install-operator-output.txt, docs/modules/hive/examples/getting_started/install-operator-output.txt.j2, docs/modules/hive/examples/getting_started/release.yaml, docs/modules/hive/examples/getting_started/release.yaml.j2, docs/modules/hive/examples/getting_started/stackablectl-hive-postgres-minio-stack.yaml, docs/modules/hive/pages/getting_started/first_steps.adoc, docs/modules/hive/pages/index.adoc, docs/templating_vars.yaml
The listener-operator is now one of the fundamental operators, along with the commons- and secret-operators, and should be mentioned accordingly everywhere.
```[tasklist]
```
```[tasklist]
```
=> docs: Add listener-operator where missing

tests/templates/kuttl/cluster-operation/10-install-hive.yaml.j2, tests/templates/kuttl/cluster-operation/20-stop-hive.yaml.j2, tests/templates/kuttl/cluster-operation/30-pause-hive.yaml.j2, tests/templates/kuttl/cluster-operation/40-restart-hive.yaml.j2, tests/templates/kuttl/logging/03-install-hive.yaml.j2, tests/templates/kuttl/orphaned-resources/01-install-hive.yaml.j2, tests/templates/kuttl/orphaned-resources/03-remove-role-group.yaml.j2, tests/templates/kuttl/resources/10-install-hive.yaml.j2, tests/templates/kuttl/smoke/60-install-hive.yaml.j2
Part of https://github.com/stackabletech/issues/issues/481
=> feat(test): pull policy IfNotPresent

CHANGELOG.md, deploy/helm/hive-operator/templates/_helpers.tpl, deploy/helm/hive-operator/templates/deployment.yaml, deploy/helm/hive-operator/templates/roles.yaml, deploy/helm/hive-operator/values.yaml
Part of: https://github.com/stackabletech/issues/issues/501
=> feat(helm): support labels in values.yaml

deploy/helm/hive-operator/values.yaml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Add Stackable vendor label to default values.yaml

tests/templates/kuttl/kerberos-hdfs/30-install-hdfs.yaml.j2
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix(tests): Remove listenerClass field, which was (somewhat) removed

tests/test-definition.yaml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore(tests): update test dependencies

docs/modules/hive/examples/getting_started/getting_started.sh.j2
corrected flags in .sh.j2 file
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> corrected flags in .sh.j2 file

docs/modules/hive/pages/index.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> docs: update supported versions text

tests/templates/kuttl/cluster-operation/40-restart-hive.yaml.j2
Fix a missing custom test template
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Fix a missing custom test template

tests/templates/kuttl/logging/01-install-hbase-vector-aggregator.yaml
Use Vector Helm chart version 0.34.0 (Vector 0.39.0) in the logging test
https://github.com/vectordotdev/helm-charts/blob/vector-0.34.0/CHANGELOG.md#vector-0340---2024-06-17
Implements stackabletech/docker-images#561
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Use Vector Helm chart version 0.34.0 in the logging test

.readme/README.md.j2, .readme/partials/main.md.j2, README.md, docs/modules/hive/examples/getting_started/getting_started.sh, docs/modules/hive/examples/getting_started/getting_started.sh.j2, docs/modules/hive/examples/getting_started/install-operator-output.txt, docs/modules/hive/examples/getting_started/install-operator-output.txt.j2, docs/modules/hive/pages/getting_started/installation.adoc, tests/templates/kuttl/logging/test_log_aggregation.py, tests/templates/kuttl/smoke/test_metastore.py
=> docs(getting-started): update stackablectl op install output

docs/templating_vars.yaml
=> fix(getting-started): Add missing template vars

tests/templates/kuttl/logging/01-install-hbase-vector-aggregator.yaml
Part of https://github.com/stackabletech/issues/issues/626
```[tasklist]
```
=> chore: Bump Vector to 0.40.0

deploy/helm/hive-operator/templates/roles.yaml
See: https://github.com/stackabletech/issues/issues/624
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix(helm): use same scc as olm

tests/templates/kuttl/logging/01-install-hbase-vector-aggregator.yaml
Upgrade the Vector aggregator in the logging tests
The Helm chart version 0.36.1 deploys Vector 0.41.1.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: Upgrade the Vector aggregator in the logging tests

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json, deploy/helm/hive-operator/crds/crds.yaml, rust/crd/src/lib.rs, rust/operator-binary/src/command.rs, rust/operator-binary/src/controller.rs, rust/operator-binary/src/kerberos.rs
Part of https://github.com/stackabletech/issues/issues/640
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: Update to operator-rs 0.77.1 and use new S3 structs

tests/templates/kuttl/smoke/test_metastore.py
Enable compression in smoketest to ensure CVE patch in https://github.com/stackabletech/docker-images/pull/922 is executed.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Enable table compression in smoke test

docs/modules/hive/examples/getting_started/getting_started.sh, docs/modules/hive/examples/getting_started/install-operator-output.txt, docs/modules/hive/examples/getting_started/release.yaml
Part of https://github.com/stackabletech/issues/issues/647.
=> docs: Update release in getting_started

docs/modules/hive/examples/getting_started/getting_started.sh, docs/modules/hive/examples/getting_started/getting_started.sh.j2
Part of https://github.com/stackabletech/issues/issues/611.
Depends on https://github.com/stackabletech/hive-operator/pull/541.
=> chore(getting_started): Replace templating instructions with make

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, Makefile, crate-hashes.json, docs/modules/hive/examples/getting_started/getting_started.sh, docs/modules/hive/examples/getting_started/getting_started.sh.j2
Add the following PRs to the release 24.11:
* #541 
* #542 
* #544
=> Update release branch

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, deploy/helm/hive-operator/Chart.yaml, docs/modules/hive/examples/getting_started/getting_started.sh, docs/modules/hive/examples/getting_started/install-operator-output.txt, docs/modules/hive/examples/getting_started/release.yaml, docs/templating_vars.yaml, tests/release.yaml, tests/templates/kuttl/upgrade/30-assert.yaml.j2, tests/templates/kuttl/upgrade/31-assert.yaml.j2
> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.
=> release: 24.11.1-rc2

.github/workflows/build.yml, CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, deploy/helm/hive-operator/Chart.yaml, docs/modules/hive/examples/getting_started/getting_started.sh, docs/modules/hive/examples/getting_started/install-operator-output.txt, docs/modules/hive/examples/getting_started/release.yaml, docs/templating_vars.yaml, tests/release.yaml, tests/templates/kuttl/upgrade/30-assert.yaml.j2, tests/templates/kuttl/upgrade/31-assert.yaml.j2
> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.
=> release: 24.11.1

docs/modules/hive/examples/getting_started/getting_started.sh, docs/modules/hive/examples/getting_started/getting_started.sh.j2
Same as https://github.com/stackabletech/hive-operator/pull/553 but this time actually in the template
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: fix minio install command in template

CHANGELOG.md, docs/modules/hive/partials/supported-versions.adoc, tests/test-definition.yaml
Readd 4.0.0 as LTS due to https://github.com/stackabletech/demos/pull/173
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Mark 4.0.1 experimental, set 4.0.0 LTS

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, deploy/helm/hive-operator/Chart.yaml, deploy/helm/hive-operator/crds/crds.yaml, docs/antora.yml, docs/modules/hive/examples/getting_started/getting_started.sh, docs/modules/hive/examples/getting_started/install-operator-output.txt, docs/modules/hive/examples/getting_started/release.yaml, docs/templating_vars.yaml, tests/release.yaml, tests/templates/kuttl/upgrade/30-assert.yaml.j2, tests/templates/kuttl/upgrade/31-assert.yaml.j2
> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.
=> chore: Release 25.3.0

tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1275
```
--- FAIL: kuttl (2509.13s)
--- FAIL: kuttl/harness (0.00s)
--- PASS: kuttl/harness/smoke_postgres-12.5.6_hive-4.0.1_openshift-false_s3-use-tls-true (311.05s)
--- PASS: kuttl/harness/kerberos-s3_postgres-12.5.6_hive-3.1.3_krb5-1.21.1_openshift-false_s3-use-tls-false_kerberos-realm-PROD.MYCORP_kerberos-backend-mit (316.03s)
--- PASS: kuttl/harness/resources_hive-4.0.1_openshift-false (35.67s)
--- PASS: kuttl/harness/resources_hive-4.0.0_openshift-false (103.80s)
--- PASS: kuttl/harness/resources_hive-3.1.3_openshift-false (39.48s)
--- PASS: kuttl/harness/upgrade_postgres-12.5.6_hive-old-3.1.3_hive-new-4.0.1_openshift-false (125.34s)
--- PASS: kuttl/harness/orphaned-resources_hive-latest-4.0.1_openshift-false (57.98s)
--- …
```
=> chore: Bump zookeeper version for 25.11.0

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json, deploy/helm/hive-operator/crds/crds.yaml, rust/operator-binary/src/main.rs
Part of https://github.com/stackabletech/issues/issues/733. This adds the EoS checker to the operator.
=> feat: Add EoS checker
